a = input('digite alguma coisa:')
print('o tipo primitivo é ', type(a))
print('é numerico? ', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é decimal? ', a.isdecimal())
print('é digito? ', a.isdigit())
print('é alfanumérico?', a.isalnum())
print('só tem espaços?', a.isspace())
print('est;a em maiusculas?', a.isupper())
print('está em minusculas?', a.islower())